version: '3'

networks:
  news-network:

services:

  config-service:
    container_name: config
    build: config
    ports:
      - "8888:8888"
    networks:
      news-network:

  news-service:
    container_name: news
    restart: always
    build: news
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
      news-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      users-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      news-network:

  users-service:
    container_name: users
    restart: always
    build: users
    ports:
      - "8081:8081"
    depends_on:
      config-service:
        condition: service_healthy
      users-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      news-network:

  news-db:
    container_name: news-db
    image: postgres:15.1
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      news-network:

  users-db:
    container_name: users-db
    image: postgres:15.1
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    networks:
      news-network:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      news-network: