server:
  port: 8081
spring:
  application:
    name: users-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  security:
    token:
      secret: Ck5HAR0cUjgPJxS9hoeVlA41OsilW5WCSleEY5bxRthen6dYBaqLtsEdfQGVy7o7
      valid-period: 3600000 # 1 hour
ru:
  clevertec:
    logging:
      enabled: true
    exception-handler:
      enabled: true